### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by dicristomanuel** [guerrerocarlos/bitcoin-live-transactions#1]
Hello! I'm using your `bitcoin-receive-payments` library. To run some tests I setup bitcore's network to be testnet: `const Networks = bitcore.Networks.testnet;`. Everything runs smoothly until I get to `bitcoin.getBalance` which come from this library. Is there a way to set it up so that it checks the testnet3 blockchain instead of the main one?

**Comment by guerrerocarlos** [comment]
Hello @dicristomanuel, I've added the testnet functionality you need, you can do as described now in the Readme:
https://github.com/guerrerocarlos/bitcoin-live-transactions#testnet
